apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sp-was-upload-pvc
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  volumeName: sp-was-upload-pv
